import React from "react";
import { Container, Typography, Box, Paper, Divider } from "@mui/material";

const PrivacyPolicy: React.FC = () => {
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Paper elevation={2} sx={{ p: 4 }}>
        <Typography variant="h3" component="h1" gutterBottom align="center">
          Privacy Policy
        </Typography>
        
        <Typography variant="body2" color="text.secondary" align="center" gutterBottom>
          Last updated: {new Date().toLocaleDateString()}
        </Typography>

        <Divider sx={{ my: 3 }} />

        <Box sx={{ "& > *": { mb: 3 } }}>
          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              1. Information We Collect
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Personal Information:</strong> When you sign in with Google, we collect your email address, 
              name, and profile information provided by Google.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Resume Data:</strong> We collect and store the resume files you upload, job descriptions 
              you provide, and the analysis results generated by our AI-powered system.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Usage Information:</strong> We track your usage of our services, including the number of 
              resume scans performed, subscription status, and feature usage patterns.
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Payment Information:</strong> Payment processing is handled securely by Stripe. We do not 
              store your credit card details on our servers.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              2. How We Use Your Information
            </Typography>
            <Typography variant="body1" paragraph>
              We use your information to:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">Provide resume analysis and optimization services</Typography>
              <Typography component="li" variant="body1">Authenticate your account and maintain your session</Typography>
              <Typography component="li" variant="body1">Process payments and manage subscriptions</Typography>
              <Typography component="li" variant="body1">Send service-related communications</Typography>
              <Typography component="li" variant="body1">Improve our AI algorithms and service quality</Typography>
              <Typography component="li" variant="body1">Comply with legal obligations</Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              3. Information Sharing and Disclosure
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>We do not sell your personal information.</strong> We may share your information only in the following circumstances:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">
                <strong>Service Providers:</strong> We use OpenAI for resume analysis and Stripe for payment processing
              </Typography>
              <Typography component="li" variant="body1">
                <strong>Legal Requirements:</strong> When required by law or to protect our rights
              </Typography>
              <Typography component="li" variant="body1">
                <strong>Business Transfers:</strong> In case of merger, acquisition, or sale of assets
              </Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              4. Data Security
            </Typography>
            <Typography variant="body1" paragraph>
              We implement industry-standard security measures to protect your information:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">SSL/TLS encryption for data transmission</Typography>
              <Typography component="li" variant="body1">Secure cloud hosting on Microsoft Azure</Typography>
              <Typography component="li" variant="body1">Regular security updates and monitoring</Typography>
              <Typography component="li" variant="body1">Access controls and authentication mechanisms</Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              5. Data Retention
            </Typography>
            <Typography variant="body1" paragraph>
              We retain your information for as long as necessary to provide our services:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">Account information: Until you delete your account</Typography>
              <Typography component="li" variant="body1">Resume data: Until you delete specific resumes or your account</Typography>
              <Typography component="li" variant="body1">Usage data: Up to 2 years for analytics purposes</Typography>
              <Typography component="li" variant="body1">Payment records: As required by law (typically 7 years)</Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              6. Your Rights and Choices
            </Typography>
            <Typography variant="body1" paragraph>
              You have the right to:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">Access and download your personal data</Typography>
              <Typography component="li" variant="body1">Correct inaccurate information</Typography>
              <Typography component="li" variant="body1">Delete your account and associated data</Typography>
              <Typography component="li" variant="body1">Opt out of marketing communications</Typography>
              <Typography component="li" variant="body1">Request data portability</Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              7. Third-Party Services
            </Typography>
            <Typography variant="body1" paragraph>
              Our service integrates with third-party providers:
            </Typography>
            <Typography component="ul" sx={{ pl: 2 }}>
              <Typography component="li" variant="body1">
                <strong>Google:</strong> For authentication (governed by Google's Privacy Policy)
              </Typography>
              <Typography component="li" variant="body1">
                <strong>OpenAI:</strong> For AI-powered resume analysis (governed by OpenAI's Privacy Policy)
              </Typography>
              <Typography component="li" variant="body1">
                <strong>Stripe:</strong> For payment processing (governed by Stripe's Privacy Policy)
              </Typography>
              <Typography component="li" variant="body1">
                <strong>Microsoft Azure:</strong> For cloud hosting and data storage
              </Typography>
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              8. International Data Transfers
            </Typography>
            <Typography variant="body1" paragraph>
              Your information may be transferred to and processed in countries other than your own. 
              We ensure appropriate safeguards are in place to protect your data in accordance with 
              applicable data protection laws.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              9. Children's Privacy
            </Typography>
            <Typography variant="body1" paragraph>
              Our service is not intended for individuals under the age of 18. We do not knowingly 
              collect personal information from children under 18.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              10. Changes to This Privacy Policy
            </Typography>
            <Typography variant="body1" paragraph>
              We may update this Privacy Policy from time to time. We will notify you of any material 
              changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom>
              11. Contact Us
            </Typography>
            <Typography variant="body1" paragraph>
              If you have any questions about this Privacy Policy, please contact us at:
            </Typography>
            <Typography variant="body1" paragraph>
              <strong>Email:</strong> privacy@resumatrix.co<br />
              <strong>Website:</strong> https://resumatrix.co<br />
              <strong>Address:</strong> Winnipeg, MB, Canada
            </Typography>
          </Box>
        </Box>
      </Paper>
    </Container>
  );
};

export default PrivacyPolicy;